print('-----------------------------------------------------------------------')
print("Dear user, welcome to the Central Bank. What is the request for Darir?")
print('-----------------------------------------------------------------------')
print('-----------------')
print('-----------------')
print('1account opening')
print('2account opening')
print('3change password')
print('-----------------')
print('-----------------')
Whichoption = input('Which option?')


if Whichoption == "1":
    print('Complete the information below.')
    name = input('name')
    lastname = input('lastname')
    Nationalcode = input('National code')
    Phonenumber = input('Phone number')
    cardpassword = ('card password')
elif Whichoption == "2":
    print('Complete the information below.')
    name = input('name')
    lastname = input('lastname')
    Nationalcode = input('National code')
    Phonenumber = input('Phone number')
    cardpassword = ('card password')
else:
    print('Complete the information below.')
    name = input('name')
    lastname = input('lastname')
    Nationalcode = input('National code')
    Phonenumber = input('Phone number')
    cardpassword = ('card password')